Implement all properties for TokenIntrospectionResponse optional claims
DuendeSoftware/foss pull request #55
Opened 2024-11-17 17:14 UTC by 0xced

As described by [RFC 7662 - OAuth 2.0 Token Introspection][1]

[1]: https://datatracker.ietf.org/doc/html/rfc7662

(Taking over https://github.com/IdentityModel/IdentityModel/pull/577 to the new repository, adapted to the new `Duende.IdentityModel` namespace.)

2024-11-21 22:10 UTC, 0xced commented
🎉 All tests are finally green ✅!

2025-01-21 14:11 UTC, josephdecock requested changes
I'd like to remove the use of `Lazy` in this PR. That way, developers can make their own choice about if they need Lazy access to these properties. My guess is that in practice, there wouldn't be much gained by not evaluating the properties when they're not needed, and depending on access patterns, the allocations needed by `Lazy` and the locking it does to provide thread safety might introduce other overhead. If we leave it out of the library, then individual applications can always add whatever optimizations they want.

2025-01-21 16:49 UTC, 0xced commented
Fair point. Addressed in 2a8c7d491b1607f4f97775bec4874d9f9a4a7341.

2025-02-05 19:58 UTC, 0xced commented
I just rebased this pull request on the `main` branch and resolved the conflicts that arose from #86.

I also slightly modified how the `exp`, `iat` and `nbf` claims are parsed to avoid throwing in case those contain an invalid number. With the previous `Lazy` implementation it would not throw before accessing them.

2025-02-23 22:48 UTC, 0xced commented
I just rebased this pull request on the main branch again.

I also slightly changed how an invalid `exp`, `iat` or `nbf` is handled, throwing an exception instead of using `null` in 930236400eaad5b77a5e5d55b8704b6527d3a1b2. Note that the exception is thrown only when accessing the respective `Expiration`, `IssuedAt` or `NotBefore` properties.

I hope this pull request will eventually get merged. 😉

2025-04-10 19:28 UTC, josephdecock commented
Thanks again for your contribution @0xced! I've rebased onto main, fixed up some merge conflicts, and simplified the error handling. I think it is fine to throw an exception right away if the introspection response includes what should be a timestamp but that doesn't parse. That let's us simplify the implementation and remove the `ExceptionDispatchInfo`s.

2025-04-10 19:29 UTC, josephdecock approved these changes

2025-04-10 19:29 UTC, merged